### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by laszlof** [tripflex/whmcs-affcoupons#46]
Hello,

While I appreciate you making updates to my code, the original license clearly states that redistribution must maintain the original license copy as well as my information.

Please either pull my original copyright and license back in, or remove this from both your website, and Github.

I'll give you a week to comply with this request before sending out an official DMCA complaint. 

Again, I don't mind that you've copied this, as the license allows it, but you must leave the original credit intact.

**Comment by seyzed** [comment]
I am not sure who you are directing at. But by any case you are directing me as your recipient, I should state that your code is junk and has no value for any sort of investment.

**Comment by laszlof** [comment]
@artaweb The message is directed at the owner of this repository. (Presumably, Myles McNamara)

Regardless of the state of the code, the fact of the matter is, the license was completely removed along with all credit for my original work. This is a violation of the license. I care nothing about any monetary gain here, I originally released this code (back in 2010) under a BSD modified license for free. Thousands of WHMCS installations used it at one point in time, I asked for no compensation for the free use of my original work. All I ask is the license remain intact along with credit to myself, as the original author.

**Comment by laszlof** [comment]
Furthermore, you can clearly see where my credit and license were removed:

https://github.com/tripflex/whmcs-affcoupons/commit/587da117fade7f4c59ca07996c81174e912ebd36

**Comment by artaweb** [comment]
Now I see why it is so important to you!

**Comment by BeZazz** [comment]
I received this via email and I have no idea who it is directed at.

**Comment by laszlof** [comment]
@BeZazz you and @artaweb are both subscribed to this repository (you both have forks of it), thats why you're getting emails. Its has nothing to do with you. Please take a moment to click on the GIthub link if you want further information.

**Comment by laszlof** [comment]
@tripflex Since you have failed to even respond to my request, I have had no choice but to file an official DMCA complaint.

Also, I find it odd that you take your own copyright material seriously, yet completely disregard my own: https://github.com/github/dmca/blob/master/2018/2018-02-15-Smyles.md

**Comment by tripflex** [comment]
I apologize @laszlof this clearly is a very old project that I am no longer maintaining, and there was no malicious intent regarding the license and the updates made.

You can clearly see this in the branch that has the original fork with my fixes:
https://github.com/tripflex/whmcs-affcoupons/tree/v2stable

The master branch is basically what I was working on to rebuild the entire plugin (without having to name it differently), not having to use any of that legacy ... forked ... codebase.  That's why as you can see, there are only a few areas of the original code that even exist, because I never got to those parts ... and really at that time, I was still learning OOP and how licensing really worked.

https://github.com/tripflex/whmcs-affcoupons/pull/9

Either way I know that doesn't mean anything in regards to the license and I apologize, because yes, I do understand and expect others to follow as well ... like I said, 4-5 years ago I had all intentions of giving credit and keeping licenses in tact, but it's been so long, I honestly have no idea what ended up happening ... besides me basically abandoning this project.

I added back the LICENSE File and updated the README file as well, if there's something else you want me to change just let me know ... i'm only leaving this up and public for others to be able to do the same thing I did from your original fork (if they want to) ... like I said, nothing was done with malicious intent ... if anything, it was just out of ignorance on my part :-\

**Comment by laszlof** [comment]
Totally understand. Thanks for following up, and thanks for re-adding the license. That is all I ask for :)

Cheers.

**Comment by tripflex** [comment]
@laszlof now ... on to regarding the DMCA ... yes, I do take my copyright material seriously, because that is a PAID licensed plugin, not just an open source project that I haven't touched in years, but my bread and butter, which people seem to love to distribute online thinking it's GPL licensed.

Regarding me "completely disregarding" your licensing .. like I said, that was not something intentional, and I had no malicious intent regarding it.  IF you want me to change anything else in the repo, or remove anything I have no problem with it, just let me know.  I will monitor this issue to make sure I see any responses and handle them accordingly, again I apologize and didn't mean to ruffle any feathers 😛

**Comment by artaweb** [comment]
What a shit show!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Myles McNamaraSent: Tuesday, 27 February 2018 03:19To: tripflex/whmcs-affcouponsReply To: tripflex/whmcs-affcouponsCc: Artaweb CO; MentionSubject: Re: [tripflex/whmcs-affcoupons] License Violation (#46)@laszlof now ... on to regarding the DMCA ... yes, I do take my copyright material seriously, because that is a PAID licensed plugin, not just an open source project that I haven't touched in years, but my bread and butter, which people seem to love to distribute online thinking it's GPL licensed.
Regarding me "completely disregarding" your licensing .. like I said, that was not something intentional, and I had no malicious intent regarding it.  IF you want me to change anything else in the repo, or remove anything I have no problem with it, just let me know.  I will monitor this issue to make sure I see any responses and handle them accordingly, again I apologize and didn't mean to ruffle any feathers 😛

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tripflex/whmcs-affcoupons","title":"tripflex/whmcs-affcoupons","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tripflex/whmcs-affcoupons"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tripflex in #46: @laszlof now ... on to regarding the DMCA ... yes, I do take my copyright material seriously, because that is a PAID licensed plugin, not just an open source project that I haven't touched in years, but my bread and butter, which people seem to love to distribute online thinking it's GPL licensed.\r\n\r\nRegarding me \"completely disregarding\" your licensing .. like I said, that was not something intentional, and I had no malicious intent regarding it.  IF you want me to change anything else in the repo, or remove anything I have no problem with it, just let me know.  I will monitor this issue to make sure I see any responses and handle them accordingly, again I apologize and didn't mean to ruffle any feathers 😛 "}],"action":{"name":"View Issue","url":"https://github.com/tripflex/whmcs-affcoupons/issues/46#issuecomment-368686647"}}}
